[game]
hostname           = "[EN][MRP][18+] Redshift [US East]"
desc               = "A social experiment."
lobbyenabled       = true
lobbyduration      = 240
round_end_pacifist = true
round_restart_time = 300
contraband_examine = false # Doubtful that it's desired at all, and would require going over every item in accordance with SOP
secret_weight_prototype = "SecretDeltaV"
role_timer_override = "DeltaV"
showgreentext = false # focus more on telling a story

[movement]
mob_pushing = false

# New players can't join a server without admins
[game.panic_bunker]
enabled = false # whitelist only anyways

[infolinks]
github     = "https://github.com/unafil/redshift"
bug_report = "https://github.com/unafil/redshift/issues/new/choose"

[net]
max_connections = 1024
tickrate = 30

[vote]
restart_required_ratio = 0.7
preset_enabled = false

[ooc]
enable_during_round = true

[whitelist]
enabled = true

[netres]
limit    = 10.0

[admin]
see_own_notes   = true
deadmin_on_join = true
allow_multi_server_play = false
[admin.alert]
min_players_sharing_connection = 2

[server]
id         = "deltav"
rules_file = "DeltaVRuleset"
uptime_restart_minutes = 2880 # 48h

[discord]
rich_main_icon_id = "deltav"

# general mrp stuff
[ic]
flavor_text = true
punctuation = true

# Disabled because it causes giga lag
#[worldgen]
#enabled = true

[rules]
time = 60

[ahelp]
admin_prefix = false
admin_prefix_webhook = false

[votekick]
enabled = false # only enabled on periapsis
eligible_number = 5
initiator_ghost_requirement = false
voter_ghost_requirement = false

[atmos]
space_wind = true

[shuttle]
arrivals = false
cooldown = 60 # 50 longer than the default
startup_time = 10 # 4.5 seconds longer than the default
travel_time = 5 # 15 seconds less than the default
emergency_dock_time = 240
emergency_transit_time_min = 30
auto_call_time = 120 # rounds are longer
auto_call_extension_time = 30 # next auto call at 2h30
emergency_early_launch_allowed = true # MRP server command ban time
recall_turning_point = 0.33

[biomass]
easy_mode = false # reclaimer can work on soul-ful bodies, mrp server

[control]
storage_limit = 5

[nf14.respawn]
time = 600
